apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dtester-pvc-initdb
  namespace: dtester
spec:
  storageClassName: standart
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 700Mi
  volumeName: dtester-initdb-mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dtester-pvc-mysql
  namespace: dtester
spec:
  storageClassName: standart
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 700Mi
  volumeName: dtester-mysql
