apiVersion: v1
kind: PersistentVolume
metadata:
  name: dtester-initdb-mysql
spec:
  storageClassName: standart
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 700Mi
  local:
    path: /home/al/initdb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - gke-c-fzd5w-default-0-b6f6e01d-dlg1
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dtester-mysql
spec:
  storageClassName: standart
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 700Mi
  local:
    path: /home/al/mysql
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - gke-c-fzd5w-default-0-b6f6e01d-dlg1
  persistentVolumeReclaimPolicy: Retain
